<?php
namespace pistol88\shop\models;

use Yii;
use yii\helpers\Url;
use pistol88\shop\models\product\ProductQuery;
use yii\behaviors\TimestampBehavior;

class Product extends \yii\db\ActiveRecord implements \pistol88\relations\interfaces\Torelate, \pistol88\cart\interfaces\CartElement
{
    public $category_ids;

    public function beforeSave($insert)
    {
        if (is_array($this->category_ids)) {
            Yii::$app->db->createCommand("DELETE FROM shop_product_to_category WHERE product_id = :product_id", [':product_id' => $this->getId()])->execute();
            foreach ($this->category_ids as $category_id) {
                Yii::$app->db->createCommand("INSERT INTO shop_product_to_category (product_id, category_id) VALUES(:product_id, :category_id)", [
                    ':product_id' => $this->getId(),
                    ':category_id' => (int) $category_id,
                ])->execute();
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->category_ids = Yii::$app->db->createCommand("SELECT category_id FROM shop_product_to_category WHERE product_id=:product_id", [
            ':product_id' => $this->getId(),
        ])->queryColumn() ?: [];

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    function behaviors()
    {
        return [
            'images' => [
                'class' => 'pistol88\gallery\behaviors\AttachImages',
                'mode' => 'gallery',
            ],
            'slug' => [
                'class' => 'Zelenin\yii\behaviors\Slug',
            ],
            'relations' => [
                'class' => 'pistol88\relations\behaviors\AttachRelations',
                'relatedModel' => 'pistol88\shop\models\Product',
                'inAttribute' => 'related_ids',
            ],
            'seo' => [
                'class' => 'pistol88\seo\behaviors\SeoFields',
            ],
            'filter' => [
                'class' => 'pistol88\filter\behaviors\AttachFilterValues',
            ],
            'field' => [
                'class' => 'pistol88\field\behaviors\AttachFields',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => time(),
            ]
        ];
    }

    public static function tableName()
    {
        return '{{%shop_product}}';
    }

    public static function Find()
    {
        $return = new ProductQuery(get_called_class());
        $return = $return->with('category');

        return $return;
    }

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['category_id', 'producer_id', 'sort', 'amount'], 'integer'],
            [['text', 'available', 'code', 'is_new', 'is_promo', 'is_popular', 'characteristics', 'equipment',
                'short_text', 'photo', 'extra', 'sales_notes'], 'string'],
            [['category_ids'], 'each', 'rule' => ['integer']],
            [['name'], 'string', 'max' => 200],
            [['slug'], 'string', 'max' => 255],

        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'code' => 'Код (актикул)',
            'category_id' => 'Главная категория',
            'producer_id' => 'Бренд',
            'name' => 'Название',
            'amount' => 'Остаток',
            'text' => 'Описание',
            'characteristics' => 'Характеристики',
            'equipment' => 'Комплектация',
            'extra' => 'Доп опции',
            'photo' => 'Картинка интерфейса',
            'short_text' => 'Краткое описание',
            'images' => 'Картинки',
            'available' => 'В наличии',
            'is_new' => 'Новинка',
            'is_popular' => 'Популярное',
            'is_promo' => 'Акция',
            'sort' => 'Сортировка',
            'slug' => 'СЕО-имя',
            'amount_in_stock' => 'Количество на складах',
            'created_at' => 'Время создания',
            'updated_at' => 'Время изменения',
            'sales_notes' => 'Описание продажи для Яндекса'
        ];
    }

    public function getId()
    {
        return $this->id;
    }

    public function minusAmount($count, $moderator="false")
    {
        $this->amount = $this->amount-$count;
        $this->save(false);

        return $this;
    }

    public function plusAmount($count, $moderator="false")
    {
        $this->amount = $this->amount+$count;
        $this->save(false);

        return $this;
    }

    public function setPrice($price, $type = null)
    {
        if($priceModel = $this->getPriceModel($type)) {
            $priceModel->price = $price;
            return $priceModel->save(false);
        } else {
            if($typeModel = PriceType::findOne($type)) {
                $priceModel = new Price;
                $priceModel->product_id = $this->id;
                $priceModel->price = $price;
                $priceModel->type_id = $type;
                $priceModel->name = $typeModel->name;

                return $priceModel->save();
            }

        }

        return false;
    }

    public function getPriceModel($type = null)
    {
        $prices = $this->getPrices();

        if(!$prices->count()) {
            return null;
        }

        if(!$type) {
            if($defaultType = yii::$app->getModule('shop')->getPriceTypeId($this)) {
                $type = $defaultType;
            } else {
                $type = 'sort';
            }
        }

        if($type == 'sort') {
            $price = $prices->where('price > 0')->orderBy('sort DESC')->one();
        } elseif($type) {
            $price = $prices->where(['type_id' => $type])->one();
        } else {
            $price = $prices->orderBy('price DESC')->one();
        }

        return $price;
    }

    public function getPrices()
    {
        return $this->hasMany(Price::className(), ['product_id' => 'id']);
    }

    public function getPrice($type = null)
    {
        if($price = $this->getPriceModel($type)) {
            return $price->price;
        }

        return null;
    }

    public function getOldprice($type = null)
    {
        if($price = $this->getPriceModel($type)) {
            return $price->price_old;
        }

        return null;
    }

    public function getProduct()
    {
        return $this;
    }

    public function getCartId() {
        return $this->id;
    }

    public function getCartName() {
        return $this->name;
    }

    public function getCartPrice() {
        return $this->price;
    }

    public function getCartOptions()
    {
        $options = [];

        if($filters = $this->getFilters()) {
            foreach($filters as $filter) {
                if($variants = $filter->variants) {
                    $options[$filter->id]['name'] = $filter->name;
                    foreach($variants as $variant) {
                        $options[$filter->id]['variants'][$variant->id] = $variant->value;
                    }
                }
            }
        }

        return $options;
        //return ['Цвет' => ['Красный', 'Белый', 'Синий'], 'Размер' => ['XXL']];
    }

    public function getName()
    {
        return $this->name;
    }

    public function getSellModel()
    {
        return $this;
    }

    public function getModifications()
    {
        $return = $this->hasMany(Modification::className(), ['product_id' => 'id'])->orderBy('sort DESC, id DESC');

        return $return;
    }

    public function getAmount()
    {
        if($amount = StockToProduct::find()->where(['product_id' => $this->id])->sum('amount')){
            return StockToProduct::find()->where(['product_id' => $this->id])->sum('amount');
        } else {
            return 0;
        }

    }

    public function getLink()
    {
        return Url::toRoute([yii::$app->getModule('shop')->productUrlPrefix, 'slug' => $this->slug]);
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['id' => 'category_id'])
            ->viaTable('{{%shop_product_to_category}}', ['product_id' => 'id']);
    }

    public function getProducer()
    {
        return $this->hasOne(Producer::className(), ['id' => 'producer_id']);
    }

    public function afterDelete()
    {
        parent::afterDelete();

        Price::deleteAll(["product_id" => $this->id]);

        return false;
    }
    public function plusAmountInStock($stock, $count){
        if($profuctInStock = StockToProduct::find()->where(['product_id' => $this->id, 'stock_id' => $stock])->one()){
            $profuctInStock->amount = $profuctInStock->amount+$count;

        } else {
            $profuctInStock = new StockToProduct();
            $profuctInStock->amount = $count;
            $profuctInStock->stock_id = $stock;
            $profuctInStock->product_id = $this->id;

        }
        return $profuctInStock;
    }

    public function minusAmountInStock($stock, $count){
        if($profuctInStock = StockToProduct::find()->where(['product_id' => $this->id, 'stock_id' => $stock])->one()){
            if($profuctInStock->amount >= $count){
                $profuctInStock->amount = $profuctInStock->amount - $count;

            } else {
                return 'На складе всего '.$profuctInStock->amount.' единиц товара. Пытались снять '.$count;
            }
        } else {
            return 'На складе нету такого товара. Пытались снять '.$count;

        }
        return $profuctInStock->save();
    }

    public function afterSave($insert, $changedAttributes) {
        parent::afterSave($insert, $changedAttributes);

        if(!empty($this->category_id) && !empty($this->id)) {
            if(!(new \yii\db\Query())
                ->select('*')
                ->from('{{%shop_product_to_category}}')
                ->where('product_id ='.$this->id.' AND category_id = '.$this->category_id)
                ->all()) {
                yii::$app->db->createCommand()->insert('{{%shop_product_to_category}}', [
                    'product_id' => $this->id,
                    'category_id' => $this->category_id,
                ])->execute();
            }
        }

        return true;
    }

    public static function getAll() {
        return Product::find()->all();
    }

    public function getFoo() {
        echo "foo";
    }
}
